task_getAll:
    path: task
    controller: App\Controller\TaskController::getTasks

task_get:
    path: task/{id}
    controller: App\Controller\TaskController::getTask

task_create:
    path: task
    controller: App\Controller\TaskController::createTask

task_update:
    path: task/{id}
    controller: App\Controller\TaskController::updateTask

task_delete:
    path: task/{id}
    controller: App\Controller\TaskController::deleteTask
